OPTION(TAGLIB "Build with TagLib support" ON)
OPTION(MEDIAINFOLIB "Build with MediaInfoLib support" ON)
OPTION(STATICPLUGINS "Build QuarkPlayer plugins in static mode" ON)
OPTION(BUILD_TESTS "Build QuarkPlayer unit tests" ON)
OPTION(WEBKIT "Build WebBrowser library with QtWebKit support" OFF)
