Document: quarkplayer
Title: Debian quarkplayer Manual
Author: <insert document author here>
Abstract: This manual describes what quarkplayer is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/quarkplayer/quarkplayer.sgml.gz

Format: postscript
Files: /usr/share/doc/quarkplayer/quarkplayer.ps.gz

Format: text
Files: /usr/share/doc/quarkplayer/quarkplayer.text.gz

Format: HTML
Index: /usr/share/doc/quarkplayer/html/index.html
Files: /usr/share/doc/quarkplayer/html/*.html


